### PR TITLE
Allow users to enter IPv6 addresses

### PR DESCRIPTION
**Pull request by bryfox**
Also support leading zero-compressed addresses.

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
Ditto with the server PR -- this looks okay to me, and works for my setup, but I'm not on an IPv6 network, I don't think.

**Comment by jthrilly** [comment]
Just a few CSS issues here with the longer IP addresses:

screenshot 2018-11-09 at 13 41 12
screenshot 2018-11-09 at 13 41 24
screenshot 2018-11-09 at 13 44 26

I will fix these up now.

One other issue is that I couldn't get "Fetch from URL" to work with an IP6 address. I was using a gist I found for simplehttpserver (https://gist.github.com/chrisklaiber/54511886e8e4c18126792fc634f44d57#file-simplehttpserver6-py), which might have been the issue. If someone else can verify it works for them, I am happy to presume its my issue.

**Comment by bryfox** [comment]
@jthrilly what URL did you enter? Are you bracketing the host (e.g., `http://[::1]:8000/foo.netcanvas`, and not `http://::1:8000/foo.netcanvas`)?

**Comment by jthrilly** [comment]
> @jthrilly what URL did you enter? Are you bracketing the host (e.g., `http://[::1]:8000/foo.netcanvas`, and not `http://::1:8000/foo.netcanvas`)?

That was it, Bryan. Thanks. I always forget about that syntax.

**Comment by bryfox** [comment]
Yeah, maybe it's worth showing an example or help text on that screen?

**Pull request merged**
