### PR TITLE
move cleartimeout to fix nodelist on quick prompt changes

### LINKED ISSUE #305: Incorrect state of Nodes on prompt change (edge cases)
NodeList#componentWillReceiveProps() involves some nested state setting and timeout-driven animations. I'm opening this issue to better understand what's happening here.

- <strike>It appears that I need to specifically cache label strings on nodes, in the case where the displayed field differs between prompts, but that shouldn't be necessary.</strike> Update: This separate issue was moved to #311.
- It appears that double-clicking the prompt can produce an incorrect state, where a node appears both in 'already mentioned' and 'nodesForPrompt'

Here's one way to reproduce the latter:

1. Reset Session
2. Load demo protocol
3. On Name generator...
4. Prompt0: Drag one or more nodes to the main list
5. Click prompt swiper to advance to Prompt1
6. Click prompt swiper to advance to Prompt2
7. Double-click prompt swiper to advance through Prompt0 to Prompt1

### PR DESCRIPTION
**Pull request by rebeccamadsen**
Fixes #305. I think this does actually fix the issue with node lists displaying the previous prompt's nodes.

### CODE REVIEW

**Comment by bryfox** [comment]
This works from my point of view 👍. I tested pretty thoroughly back at #313, and if there's still an edge case, I can't find it.

**Comment by jamieshark** [comment]
The only other thing I might add is to clear the timeout on `componentWillUnmount` as well.

**Comment by rebeccamadsen** [comment]
Good point @jamieshark. I've added that in as well.

**Comment by jthrilly** [comment]
Looks good to me!

**Pull request merged**
