### PR TITLE
Fix sociogram centering

### LINKED ISSUE #659: Sociogram: Cannot pick up nodes dropped around timeline
Two versions ago, the sociogram was offset from the left edge of the viewport; now it extends to the left edge and overlaps with the timeline. If a node is dropped there, it cannot be picked up again; the timeline (including transparent area) is used as the side menu trigger.

### PR DESCRIPTION
**Pull request by bryfox**
Fixes #659.

This cleans up centering by moving style definitions to a mixin, and prevents sociogram nodes from begin dropped on top of the timeline/menu area. The Sociogram also gets a little bit of T/R/B margin so that node labels aren't cut off when dropped at the edges.

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
I'm okay with this, but I think @jthrilly wants sociogram to take the whole screen space and use "exclusion zones" as the fix for #371 eventually, so I defer to him.

**Comment by bryfox** [comment]
Ah, I didn't realize this was intentional. If we want to keep the occlusion for now, I can update this to revert the Sociogram centering but keep the other cleanup; that's going to make my life easier in some future work.

**Comment by jthrilly** [comment]
So in general I did want to keep the interfaces centred, but I can see the logic of having them offset against the timeline. I think we should try it the way it is implemented here and see if others find it as disturbing as I do! 😅 

The main "fix" here (preventing node drop on the timeline) works nicely, with the exception that returning the node to its last location when dropped on an invalid location is a bit jarring. Probably we will fix the underlying behaviour with #371, but just to document here what the ideal behaviour should be:

- Nodes hovering over an exclusion zone should enter an invalid state
- If dropped on an exclusion zone, they should animate back to their last valid position

**Comment by bryfox** [comment]
For centering, I guess I followed the lead of the Name Generator. If it's disturbing, we could adjust [the right margin](https://github.com/codaco/Network-Canvas/pull/660/files#diff-02ad984811a3111f39d328f15ebb70f5R15) (and `interface-prompt` if needed), then special case the NG. Or revert this :) ...in part, I was just trying to avoid coupling every interface individually to the timeline.

**Pull request merged**
