### PR TITLE
Decode URI component for download urls for local paths

### PR DESCRIPTION
**Pull request by wwqrd**
Tiny fix to ensure downloaded urls generate URI decoded paths.

Is marked as WIP because this needs to be tested on devices,
which is waiting on PR https://github.com/codaco/Network-Canvas/pull/533

### CODE REVIEW

**Comment by bryfox** [comment]
I tested "Import by URL" (with filename spaces) successfully on macOS & Android. However, iOS errors.

The plugin [converts target to an escaped URL](https://github.com/apache/cordova-plugin-file-transfer/blob/master/src/ios/CDVFileTransfer.m#L442-L449), but then later [fails this check against the unescaped string](https://github.com/apache/cordova-plugin-file-transfer/blob/master/src/ios/CDVFileTransfer.m#L461).

I suppose there are a couple of paths forward. Since this plugin is [deprecated in favor of xhr](https://github.com/apache/cordova-plugin-file-transfer#deprecated), might it make sense to switch to that now?

**Comment by wwqrd** [comment]
From what you've described it sounds like an issue with the file system for cordova? Which probably means that we need to change how protocols are loaded too. I'm tempted to use %20 thoughtout.

**Comment by jthrilly** [comment]
Another way of looking at this is that we don't actually have to preserve the original filename when storing the protocol internally. If this is causing a headache, we could rename them to something every platform supports? Not a plan of action, just a thought.

**Comment by jthrilly** [comment]
Could even use the new UUID util to generate names?

**Comment by wwqrd** [comment]
Generating local names would make a lot of sense, and help to avoid collisions between protocols. I'll update it to do that instead.

**Comment by wwqrd** [comment]
Using a hash type file name is simple enough, but incorporating the actual protocol name into sessions seems complex.

I've found a way using a thunk, but it feels quick and dirty, as it depends on the protocol being loaded into state and updates the name each time session is updated - if anyone has an idea of a more appropriate placement I'd appreciate the feedback!

**Comment by wwqrd** [comment]
Okay, having looked at this some more I think adding protocol titles to sessons probably falls within the scope of https://github.com/codaco/Network-Canvas/issues/545. So I'm going to request a merge with the file names still set as the protocol names.

**Pull request merged**
