### PR TITLE
Feature/webpack 3

### PR DESCRIPTION
**Pull request by jthrilly**
This PR updates webpack to 3.x (#203) and removes the need for the `$font-path` variable. It requires `network-canvas-ui#webpack-3`. Probably a good idea to hose `node_modules` and install from fresh, too. The yarn package lock may not be up to date, so please feel free to update it.

Other changes:

- Updated many dependencies
- Organized package.json
- Removes duplicate font files

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
Chrome worked fine for me, but I can't get `yarn run build` or `npm run build` to work:
```
PS C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas> npm run build

> network-canvas@4.0.0-alpha.1 build C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas
> node scripts/build.js

Creating an optimized production build...
C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\Compilation.js:219
                                _this.errors.push(err);
                                     ^

TypeError: Cannot read property 'errors' of null
    at errorAndCallback (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\Compilation.js:219:1
0)
    at errorOrWarningAndCallback (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\Compilation
.js:251:14)
    at factoryCallback (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\Compilation.js:264:13
)
    at factory (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\NormalModuleFactory.js:235:20
)
    at resolver (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\NormalModuleFactory.js:60:20
)
    at asyncLib.parallel.e (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\NormalModuleFacto
ry.js:127:20)
    at C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\async\dist\async.js:3861:9
    at C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\async\dist\async.js:996:13)
    at C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\async\dist\async.js:906:16
    at C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\async\dist\async.js:3858:13
    at resolvers.normal.resolve (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\webpack\lib\NormalModule
Factory.js:119:22)
    at onError (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\enhanced-resolve\lib\Resolver.js:59:18)
    at loggingCallbackWrapper (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\enhanced-resolve\lib\creat
eInnerCallback.js:31:19)
    at innerCallback (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\enhanced-resolve\lib\Resolver.js:14
2:19)
    at loggingCallbackWrapper (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\enhanced-resolve\lib\creat
eInnerCallback.js:31:19)
```

I also saw this:
errors
but I've seen this in other branches, so I suspect it is an issue in (a) master and (b) the protocols.

Once in Chrome the app sent me back to the setup screen unexpectedly, but I could not duplicate it no matter what I tried. Fortunately, but unfortunately.

**Comment by rebeccamadsen** [comment]
If I remove `bail: true` in webpack.config.prod.js, as per [this suggestion](https://github.com/webpack/webpack/issues/3324#issuecomment-289720345), then the error when trying to run build is:
```

PS C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas> npm run build

> network-canvas@4.0.0-alpha.1 build C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

./src/styles/main.scss
Module not found: You attempted to import ../../../assets/fonts/quicksand-latin-300.eot which falls outside of the project
 src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink
to it from project's node_modules/.
```

**Comment by jthrilly** [comment]
Turns out that I am a total idiot.

(I didn't update the production webpack config with the font path changes. Pushing an update now).

The linting errors are interesting. I think we are in a bit of a mess with linting generally, and I suspect that different IDEs/editors/platforms are picking up and implementing different rules. It is out of scope for this issue, but I do want you to be able to test this webpack config at least. If you need to make a temporary change to let this run properly, please go ahead just to make sure the compilation is working.

**Comment by rebeccamadsen** [comment]
Okay, I can build now, and run in Chrome and Cordova. But electron gives me this:

```
App threw an error during load
Error: Cannot find module 'electron-log'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\node_modules\electron\dist\re
sources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\www\electron-starter.js:4:13)
    at Object.<anonymous> (C:\Users\Big Baloo\Documents\GitHub\NetworkCanvas\www\electron-starter.js:59:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

Also tests need to be updated.

I don't think the other bug I saw was a linting issue, I think it was the protocol file. Auto-populate nickname has issues when the name field is blank or has no spaces. Previous webpacks just put the error on the console, but this one throws a whole screen in my face to let me know (when you run in debug mode -- it won't do that in production!).

**Comment by rebeccamadsen** [comment]
Electron will work for me if I add `electron-log` and `electron-updater` to the dependencies. And cordova just took it upon itself to add itself to dependencies? So my package.json looks like this:
```
  "dependencies": {
    "cordova-android": "^6.2.3",
    "cordova-ios": "^4.5.0",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-x-socialsharing": "^5.2.0",
    "electron-log": "^2.2.7",
    "electron-updater": "^2.7.2"
  },
```
Tests look like a simple spacing/comment issue easily resolved.

**Comment by jthrilly** [comment]
> Electron will work for me if I add electron-log and electron-updater to the dependencies.

Ah, these are in the _second_ package.json, which gets used in the packaged app. They need to be a dev-dependency in the main package.json too, because this is what is used when we run electron without packaging. 

The Cordova ones are coming from config.xml, but they are already in dev dependencies. It looks like Cordova adds itself to dependencies as soon as it is invoked. Annoying, but tolerable as long as it isn't getting bundled with the build packages (which it isn't).

**Comment by rebeccamadsen** [comment]
Ah makes sense. Everything looks great on my system! Just the sociogram test is failing, but after that I think this is a go.

**Pull request merged**
