### PR TITLE
Feature/form builder

### PR DESCRIPTION
**Pull request by wwqrd**
Addresses: https://github.com/codaco/Network-Canvas/issues/123

Not exactly finished, but looking for feedback on the code.

For example stuff like `withNetworkData` probably ought to live somewhere else?

It's quite heavily shimmed, as I'm expecting the field components to end up in https://github.com/codaco/Network-Canvas-UI. Some already are.

### CODE REVIEW

**Comment by jthrilly** [comment]
I'm not going to be able to look at this until much later in the week, any possibly not until next week. Anyone else able to help?

**Comment by rebeccamadsen** [comment]
I am not able to run this locally, but just looking at the code I can agree `withNetworkData` probably makes sense to pull out. I'm not completely sure where it would make the most sense though.

**Comment by jthrilly** [comment]
So, what's with all the failed tests? Not written yet? 

I'm going to check this out now.

**Comment by jthrilly** [comment]
Did this get merged?

**Comment by rebeccamadsen** [comment]
It looks like this was merged in a [different PR](https://github.com/codaco/Network-Canvas/pull/173).

**Comment by jthrilly** [comment]
👍

**Pull request closed without merging**
