### PR TITLE
Feature/optimise roster

### LINKED ISSUE #941: Name generator (large roster) interface and very large datasets
A user needs to be able to use large 50,000+ external data sets within the roster interface. 

We have a sample dataset containing example data, the and the app does seem to work correctly (ask me for a copy if you want to test). However, performance is too poor to be realistically usable. 

Can we improve the performance of very large datasets using this interface? Some thoughts:

- Are we correctly debouncing so that searches are not being triggered too aggressively as the user is typing?
- Are there other libraries than fuse.js that would perform better? 
- Is DOM shredding or some other rendering problem impacting performance?
- How do search accuracy and search fields impact performance? Can we limit either to improve the situation here?

Some discussion of performance with fuse here: https://github.com/krisk/Fuse/issues/282

### PR DESCRIPTION
**Pull request by wwqrd**
Functionally complete update of CardList component to use virtualised dom, which allows comfortable display of >50k cards.

Also includes loading states for large roster (NameGeneratorAutoComplete)

Todo:
- [x] Update styles to match previous scrollable component
- [x] Show question prompt whilst data is loading (maybe show input greyed out?).

Notes:
- Because cards are rendered by row using JS, the column count is now determined in JS. Thoughts? Currently naively takes ratio at component mount time, and doesn't update when window changes size (until component is remounted)
- Based on the memory requirements of loading this much data, and the limited API available in cordova to reduce it, this feature is going to be considered "desktop only". Where should we put that info?

Resolves #941

### CODE REVIEW

**Comment by wwqrd** [comment]
> Looking amazing! When you say "this feature" would be desktop only, is that the NameGeneratorAutoComplete interface, or the optimizations, or also the NameGeneratorList? What would the mobile version do instead?

Interesting point, maybe the notice could go on the NameGeneratorAutoComplete builder in Architect. We could even build another "external data" input which monitors the file size.

The interfaces are still usable on both mobile and desktop currently, and the rendering improvements are applicable to both. However, if a user wants to use NameGeneratorAutoComplete they will need to use smaller datasets in the 100s.

> The cards at the bottom can be super long, not sure if that bothers anyone

Should be fixed now

> One requested change: the "sort" buttons on NameGeneratorList (e.g. "nickname" and "age" on "previous interview JSON") sometimes don't make the view update. If I do a sort, it sometimes will update the view and sometimes not. But if I do a sort, and then filter, the sort shows, so could just be a refresh issue.

I'll take a look at this now.

**Comment by wwqrd** [comment]
https://github.com/codaco/Network-Canvas/pull/951/commits/b64142a066be1cd20d279ed69805cc2b75b8258e Should fix the list re-render when sort/filter changes.

**Comment by rebeccamadsen** [comment]
Updates look good, and I agree that some sort of warning and/or check on data set size in architect would make sense. I just see one small warning on the console:

```
Warning: Failed prop type: The prop `awaitingResults` is marked as required in `Search`, but its value is `undefined`.
    in Search (created by withHandlers(Search))
    in withHandlers(Search) (created by lifecycle(withHandlers(Search)))
    in lifecycle(withHandlers(Search)) (created by withPropsOnChange(lifecycle(withHandlers(Search))))
    in withPropsOnChange(lifecycle(withHandlers(Search))) (created by withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))
    in withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))) (created by Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))
    in Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))) (created by withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))
    in withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))) (created by Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))))
    in Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))) (created by mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))))
    in mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))) (created by lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))))))
    in lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))))) (created by withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))))))
    in withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))))) (created by withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))))))))
    in withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))))))) (created by withState(withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))))))))
    in withState(withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))))))) (created by Connect(withState(withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))))))))))
    in Connect(withState(withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search))))))))))))) (created by defaultProps(Connect(withState(withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))))))))))
    in defaultProps(Connect(withState(withState(withHandlers(lifecycle(mapProps(Connect(withStateHandlers(Connect(withHandlers(withPropsOnChange(lifecycle(withHandlers(Search)))))))))))))) (at NameGeneratorAutoComplete.js:84)
    in div (at NameGeneratorAutoComplete.js:83)
    in div (at NameGeneratorAutoComplete.js:64)
    in NameGeneratorAutoComplete (created by Connect(NameGeneratorAutoComplete))
    in Connect(NameGeneratorAutoComplete) (at withPrompt.js:43)
    in WithPrompt (created by Connect(WithPrompt))
    in Connect(WithPrompt) (at Stage.js:25)
    in StageErrorBoundary (at Stage.js:23)
    in div (at Stage.js:22)
    in div (at Stage.js:21)
    in Transition (at Stage.js:35)
    in Stage (at ProtocolScreen.js:139)
    in div (created by TransitionGroup)
    in TransitionGroup (at ProtocolScreen.js:135)
    in div (at ProtocolScreen.js:126)
    in Protocol (created by Connect(Protocol))
    in Connect(Protocol) (at withPrompt.js:43)
    in WithPrompt (created by Connect(WithPrompt))
    in Connect(WithPrompt) (at LoadParamsRoute.js:51)
    in LoadParamsRoute (created by Connect(LoadParamsRoute))
    in Connect(LoadParamsRoute) (at routes.js:45)
    in Switch (at routes.js:43)
    in Unknown (at src/index.js:36)
    in div (at App.js:78)
    in div (at App.js:66)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App)) (at src/index.js:35)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at src/index.js:34)
    in PersistGate (at src/index.js:33)
    in Provider (at src/index.js:32)
```

**Comment by wwqrd** [comment]
@rebeccamadsen Should be fixed now

**Pull request merged**
