### PR TITLE
Teaching Protocol

### LINKED ISSUE #322: Implement the educational factory protocol
Using the documentation prepared during the previous months (details available to team members upon request), implement as much as the educational protocol as possible, as a "factory" protocol within network canvas.

### PR DESCRIPTION
**Pull request by jthrilly**
This PR adds the educational/teaching protocol developed by the team (closes #322). Some features, notably the ordinal bin, are not yet implemented, but the protocol configuration has been written. This requires the latest version of Network-Canvas-UI. 

One change is outstanding: create a short movie that shows the node linking process

Please file issues for any bugs you see with this PR that **do not result from changes added in this PR**. These will be fixed in the next release. Issues introduced here will be fixed in this PR as usual.

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
This is pretty well laid out! I had some comments, a few typos, and a few things that maybe are separate issues:
- Welcome page references a nonexistent "Continue" button
- the toggle button on the node form doesn't quite fit (probably not a bug introduced here, though)
- Also probably not introduced here, just something we haven't come across yet:
```
Warning: React does not recognize the `isNumericOnly` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isnumericonly` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by ToggleInput)
```
- The RadioGroup for gender doesn't have an error message. Not sure if it is provided but not showing, or just not provided. But it seems to be required.
- The Arranging nodes page, second bullet point should be "Place" not "Please".
- The "Reset" button on the sociogram throws an error.
```
Sociogram.js:69 Uncaught TypeError: Cannot read property 'creates' of undefined
    at Sociogram.js:69
    at Array.forEach (<anonymous>)
    at Sociogram.js:67
    at Recompose.js:251
    at onClick (Sociogram.js:42)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at Object.invokeGuardedCallback (react-dom.development.js:438)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:452)
    at executeDispatch (react-dom.development.js:836)
    at executeDispatchesInOrder (react-dom.development.js:858)
    at executeDispatchesAndRelease (react-dom.development.js:956)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:967)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (react-dom.development.js:935)
    at processEventQueue (react-dom.development.js:1112)
    at runEventQueueInBatch (react-dom.development.js:3607)
    at handleTopLevel (react-dom.development.js:3616)
    at handleTopLevelImpl (react-dom.development.js:3347)
    at batchedUpdates (react-dom.development.js:11082)
    at batchedUpdates (react-dom.development.js:2330)
    at dispatchEvent (react-dom.development.js:3421)
```
- Exporting Data references "the option" but doesn't specify which. The option is called "Download Data" so there is a small disconnect there between export and download.

**Comment by rebeccamadsen** [comment]
Oh one more. On Android emulator the "Drawing Ties" screen doesn't show the image, and the inspected console shows this error:
```
Refused to load the image 'android-webview-video-poster:default_video_poster/-141442556822233072' because it violates the following Content Security Policy directive: "img-src asset: 'self' data: cdvfile: file:".

index.html#/protocol:1 Uncaught (in promise) FileError
```
Chrome and Electron had no problem with the image.

And I think we want plural "relationships" on that same page instead of singular. ("a way to show relationship between people")

**Comment by jthrilly** [comment]
Looks like video doesn't work in Android, then. :(

**Comment by jthrilly** [comment]
@rebeccamadsen - can you look into why?

**Pull request merged**
