### PR TITLE
Feature/sociogram interface

### PR DESCRIPTION
**Pull request by wwqrd**
Implementation for issue #126 

To test:

1. The first time you run this (with a clean state), you'll need to add some nodes first, this can be done from the dev console with `populateNodes(n)`, e.g. `populateNodes(5)`.
1. The sociogram inteface contains the following prompts:
    1. Position nodes on a radar view from the node bucket
    1. Add edges between nodes (friends), but not position them
    1. Select nodes (to add attributes), but not position them.
    1. Position nodes on another layout, and add a different edge between nodes (family).
    1. Position nodes on a background image from the node bucket, whist showing 'family' edges, but not allow the edges to be altered.

### CODE REVIEW

**Comment by wwqrd** [comment]
Okay, those changes are up with the following caveats:

- I didn't add drop shadows to the edges. I think this may be possible, using filters (this is the approach I didn't have success with). Alternatively we could fully render the edge layer with an offset for a pseudo shadow effect.
- We are separating out the filters into another issue.
- The reset breaks some of the tests
- Still need to add that dialog style to the prompts (note to self)

**Comment by wwqrd** [comment]
Okay, fixed the following:

- ~The reset breaks some of the tests~
- ~Still need to add that dialog style to the prompts (note to self)~

Ready to merge if you're otherwise happy with it.

**Comment by pfsj** [comment]
Moving around using the menu seems to break the coordinates of the edges relative to the nodes. See the before or after below. This happens both in the browser and built versions. 

At the edge creation screen, additional edges will still be created but they will appear at the coordinates of the original nodes, not where they appear on screen - despite having to click on the nodes where they appear on the screen to create those edges.

screen shot 2017-08-23 at 10 29 28 am

screen shot 2017-08-23 at 10 29 42 am

**Comment by pfsj** [comment]
Not sure if this is an issue because I'm uncertain of the permanence of the "Reset Layout" feature. But, "Reset Layout" keeps the edges that were placed on the sociogram once two or more nodes that were connected are placed back on the sociogram.

**Comment by jthrilly** [comment]
The requestAnimationFrame fix has caused the following error when switching between stages:

```
getAbsoluteBoundingRect.js:42 Uncaught TypeError: Cannot read property 'scrollLeft' of null
    at getAbsoluteBoundingRect (getAbsoluteBoundingRect.js:42)
    at Droppable._this.updateZone (droppable.js:43)
    at invokeFunc (lodash.js:10350)
    at trailingEdge (lodash.js:10397)
    at timerExpired (lodash.js:10385)
```

I think this refers to a droppable component on the _previous_ interface, and is happening because the DOM object has been destroyed by the time `getAbsoluteBoundingRect()` is called.

**Pull request merged**
