### PR TITLE
Rewrite of protocol file downloading/loading and implementation of local protocol import

### PR DESCRIPTION
**Pull request by jthrilly**
Summary of changes:

- Refactor async action handling for protocol installation to use Thunks rather than Epics. Two thunks added to cover download and install from URL, and install from local file.
- Completely reworked protocol import overlay, which handles local file import, remote URL import, and import from paired Server.
- Validation of protocols is enforced on import, meaning invalid protocol files cannot be imported.
- Rename actions to more accurately reflect what they do. For example `loadProtocol` became `parseProtocol`.
- Removing concept of 'factory protocols' so that all protocols are handled in the same way. Dev workflow now implemented via "download development protocol" button.
- Protocol validation moved to git submodule.
- Re-oganise the state in several ways:
  - `session` -> `activeSessionId`
  - 'sessions[activeSessionId]` now stores pointer to `installedProtocols[protocolUID]`
  - `protocol` -> `importProtocol` (used as temporary state for the download/extract/parse flow state.
  - `protocols` -> `installedProtocols` (now used to store the contents of `protocol.js` after extraction)
- Reworking of router path to remove two-way relationship between session state and router path. Path is now derived from session state and only used for interface selection and loading. Path changes do not update state.
- Temporary removal of some tests in anticipation of revised testing strategy in Beta-1.

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
This is a big change! I think it makes things easier to reason with. Here are things I've noticed in poking around. I can take a look at any.

* I'm having trouble getting a "valid" protocol from architect to NC with anything other than information stages. The schema doesn't like how we're changing forms yet, and quick add is expecting just a boolean.
* Skip logic isn't working. "Testing markdown" screen cycles to itself when trying to move forward. "Finish Interview" cycles to itself when trying to move backward. If you try to navigate to skip logic screen via the menu, you cycle to your current stage instead of the one after the skip logic stage.
* Exporting a file gives me an error that says "Something went wrong! 'uuid' and 'data' required on session".
* "Initialising protocol import..." (do we care whether it is American or British English spelling for "initializing"?). Also, not a change from this branch, but in the settings menu is another spelling instance: "The full screen node form is optomised"... (vs optimized).
* Nodes all show "undefined" inside the categories in Categorical Bin for the development protocol, with this warning:
```
Warning: Failed prop type: The prop `displayVariable` is marked as required in `CategoricalList`, but its value is `undefined`.
    in CategoricalList (at Monitor.js:34)
    in Monitor (created by Connect(Monitor))
    in Connect(Monitor) (at CategoricalBin.js:42)
    in div (at CategoricalBin.js:25)
    in CategoricalBin (created by Connect(CategoricalBin))
    in Connect(CategoricalBin) (at withPrompt.js:43)
    in WithPrompt (created by Connect(WithPrompt))
    in Connect(WithPrompt) (at Stage.js:25)
    in StageErrorBoundary (at Stage.js:23)
    in div (at Stage.js:22)
    in div (at Stage.js:21)
    in Transition (at Stage.js:35)
    in Stage (at ProtocolScreen.js:119)
    in div (created by TransitionGroup)
    in TransitionGroup (at ProtocolScreen.js:115)
    in div (at ProtocolScreen.js:106)
    in Protocol (created by Connect(Protocol))
    in Connect(Protocol) (at withPrompt.js:43)
    in WithPrompt (created by Connect(WithPrompt))
    in Connect(WithPrompt) (at LoadParamsRoute.js:65)
    in LoadParamsRoute (created by Connect(LoadParamsRoute))
    in Connect(LoadParamsRoute) (at routes.js:45)
    in Switch (at routes.js:43)
    in Unknown (at src/index.js:35)
    in div (at App.js:50)
    in div (at App.js:39)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App)) (at src/index.js:34)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at src/index.js:33)
    in PersistGate (at src/index.js:32)
    in Provider (at src/index.js:31)
```
* Navigating to finish session stage gives this warning:
```
Warning: Failed prop type: The prop `sessionId` is marked as required in `FinishSession`, but its value is `undefined`.
    in FinishSession (created by Connect(FinishSession))
    in Connect(FinishSession) (at Stage.js:25)
    in StageErrorBoundary (at Stage.js:23)
    in div (at Stage.js:22)
    in div (at Stage.js:21)
    in Transition (at Stage.js:35)
    in Stage (at ProtocolScreen.js:119)
    in div (created by TransitionGroup)
    in TransitionGroup (at ProtocolScreen.js:115)
    in div (at ProtocolScreen.js:106)
    in Protocol (created by Connect(Protocol))
    in Connect(Protocol) (at withPrompt.js:43)
    in WithPrompt (created by Connect(WithPrompt))
    in Connect(WithPrompt) (at LoadParamsRoute.js:65)
    in LoadParamsRoute (created by Connect(LoadParamsRoute))
    in Connect(LoadParamsRoute) (at routes.js:45)
    in Switch (at routes.js:43)
    in Unknown (at src/index.js:35)
    in div (at App.js:50)
    in div (at App.js:39)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App)) (at src/index.js:34)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at src/index.js:33)
    in PersistGate (at src/index.js:32)
    in Provider (at src/index.js:31)
```

**Comment by jthrilly** [comment]
> * "Initialising protocol import..." (do we care whether it is American or British English spelling for "initializing"?). Also, not a change from this branch, but in the settings menu is another spelling instance: "The full screen node form is optomised"... (vs optimized).
> * Nodes all show "undefined" inside the categories in Categorical Bin for the development protocol, with this warning:

I've fixed these two just now :) thanks!

**Comment by jthrilly** [comment]
> * Skip logic isn't working. "Testing markdown" screen cycles to itself when trying to move forward. "Finish Interview" cycles to itself when trying to move backward. If you try to navigate to skip logic screen via the menu, you cycle to your current stage instead of the one after the skip logic stage.
> * Exporting a file gives me an error that says "Something went wrong! 'uuid' and 'data' required on session".

These two will be fixed here: https://github.com/codaco/Network-Canvas/pull/882

**Comment by jthrilly** [comment]
> * I'm having trouble getting a "valid" protocol from architect to NC with anything other than information stages. The schema doesn't like how we're changing forms yet, and quick add is expecting just a boolean.

This one is going to be trial and error. Final step with this is implementing protocol validation in architect, too.

**Comment by wwqrd** [comment]
> Reworking of router path to remove two-way relationship between session state and router path. Path is now derived from session state and only used for interface selection and loading. Path changes do not update state.

This looks much better, I think it might be worth removing stageIndex from routes too. I think some of the naming could be improved re route components, if we are keeping routes.

Some of the tests rely on quite big state objects. Perhaps these could be shared to keep everything in sync.

Great to have the validation feature! I didn't test every scenario (I think the validation repo should handle that), but I did try and load a broken protocol and got a sensible error!

It's difficult to properly review the changes on account of the scale, but I think this is clearly a net gain 👍

**Comment by jthrilly** [comment]
> Some of the tests rely on quite big state objects. Perhaps these could be shared to keep everything in sync.

Yeah, I am hoping you'll be able to offer some advice on this in July when we look at a new strategy for tests and try to improve our coverage. I think we can do something much more smart.

**Pull request merged**
